config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "application#welcome"
  # get "/home" => "application#home", as: "homepage"
  get "/auth/facebook/callback" => "sessions#create"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  post "/logout" => "sessions#destroy"
  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :movies, only: [:show, :index, :new, :edit, :destroy]
  end
  resources :genres, only: [:index, :show]
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :user_genres
  has_many :users, through: :user_genres
  has_many :movies_genres
  has_many :movies, through: :movies_genres
  validates :name, inclusion: { in: %w(Horror Comedy Thriller Drama Action Documentary Romance Mystery Family Animation) }
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :movies_genres
  has_many :genres, through: :movies_genres
  belongs_to :user

  validate :is_date_format
  validates :title, :actors, :director, :description, presence: true

  def build_movie_genres(params)
    @movie = Movie.find(params[:id])

    params[:movie][:genres].each do |genre|
      if !genre.empty?
        @movie.movies_genres.build(:genre_id => genre)
        @movie.save
      end
    end
  end

  def self.upcoming_movies
    where("release_date > ?", Date.today).order(release_date: :desc)
  end

  def self.by_genre(genre_name)
    self.joins(:genres).where(genres: { name: genre_name })
  end

  def self.by_title(title)
    where(title: title)
  end
  def self.by_director(director)
    where(director: director)
  end

  private

  def is_date_format
    return true if self.release_date == "nil"
    self.release_date.to_date ? true : errors.add(:release_date, "You must enter a valid date, for example: Jun 12, 2016")
  end
end

app/models/movies_genre.rb
class MoviesGenre < ActiveRecord::Base
  belongs_to :movie
  belongs_to :genre
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :user_genres
  has_many :genres, through: :user_genres

  has_many :movies
  validates :name, :email, presence: true
  validates :email, uniqueness: true, :if => :new_record?
  has_secure_password

  def set_default_role
    self.role ||= :user
  end

  def build_user_genres(params)
    @user = User.find_by(email: params[:user][:email])
    params[:user][:genres].each do |genre|
      if !genre.empty?
        @user.user_genres.build(:genre_id => genre)
        @user.save
      end
    end
  end

  def self.find_or_create_by_omniauth(auth)
    self.where(email: auth["info"]["email"]).first_or_create do |user|
      user.name = auth["info"]["name"]
      user.password = SecureRandom.hex
      user.image = auth["info"]["image"]
      user.email = auth["info"]["email"]
      user.uid = auth["uid"]
    end
  end
end

app/models/user_genre.rb
class UserGenre < ActiveRecord::Base
  belongs_to :user
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def welcome
    @user = User.find_by(id: session[:user_id])
  end

  def home
    @user = User.find_by(id: session[:user_id])
  end

  def current_user
    @user = (User.find_by(id: session[:user_id]) || User.new)
  end

  private

  def logged_in?
    if !current_user
      redirect_to "/login"
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :logged_in?, :except => [:show, :index]

  #before_action :admin_only, :except => [:show, :index]

  def index
    #@movies = Movie.all
    @genres = Genre.all
    if !params[:genre].blank?
      @movies = Movie.by_genre(params[:genre])
      @search_genre = params[:genre] #MVC, used for styling page
    elsif params[:date] != nil
      @movies = Movie.upcoming_movies
    else
      @movies = Movie.all
    end

    #elsif !params[:by_title].blank?
    # @movies = Movie.by_title(params[:])
  end

  def show
    if params[:user_id]
      @movie = User.find(params[:user_id]).movies.find(params[:id])
    else
      @movie = Movie.find(params[:id])
    end
  end

  def new
    @movie = Movie.new(user_id: params[:user_id])
    @genres = Genre.all
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.build_movie_genres(params)

    if @movie.valid?
      @movie.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.build_movie_genres(params)
    #@user = set_user

    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def edit
    @movie = Movie.find(params[:id])
    @genres = Genre.all
  end

  def destroy
    movie = Movie.find(params[:id])
    movie.destroy
    redirect_to user_movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :description, :preview, :actors, :director, :genres, :release_date, :user_id)
  end

  # def admin_only
  #   unless current_user.role == "admin"
  #     redirect_to root_path, :alert => "Access denied."
  #   end
  # end

  # if movie.release_date > todays.datetime
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      @user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = @user.id
      redirect_to @user
    else
      user = User.find_by(email: params[:user][:email])
      user = user.try(:authenticate, params[:user][:password])
      if !user
        redirect_to(controller: "sessions", action: "new")
      end
      session[:user_id] = user.id
      @user = user

      redirect_to user_path(@user)
    end
  end

  def destroy
    session.delete :user_id

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @genres = Genre.all
  end

  def create
    @user = User.new(user_params)
    @user.build_user_genres(params) unless !params[:user][:genres]

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @genres = Genre.all
  end

  def update
    @user = User.find(params[:id])

    @user.update(user_params) unless !@user.save
    redirect_to @user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :uid, :image, :password_confirmation, :genres, :movies)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def youtube_video(preview)
    render :partial => "movies/video", :locals => { :preview => preview }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movie_helper.rb
module MovieHelper
  def is_user_movie?(movie)
    movie.user_id == session[:user_id] ? true : false
  end
end

app/views/application/welcome.html.erb
<div class="ui raised very padded container segment">
  <h1 class="ui header">Welcome to Flicks</h1>
  <p>Flicks is an application for ALL movie lovers. We make sure you don't miss out on new movies by providing you with latest trailers and release information. All you have to do is choose what kind of films you are into and we take care of the rest. If you haven't joined the party already, <%= link_to "sign up now", new_user_path %>!</p>
</div>

app/views/genres/index.html.erb
<h2> Movies by Genre </h2>
<% @genres.each do |g|%>
   <h4> <%= g.name %> </h4>
    <ul>
        <% g.movies.each do |movie| %>
            <li><%= link_to movie.title, movie_path(movie) %>  <%= movie.release_date %></li> 
        <%end%>

    </ul>
<%end%>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>
<ul>
    <% @genre.movies.each do |movie| %>
        <h3><%= link_to movie.title, movie_path(movie) %></h3> 
        <li><%= movie.release_date %></li> 
        <li><%= youtube_video movie.preview %></li>
    <%end%>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flicks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  </head>

  <body>
  <header>
    <div class="ui attached stackable menu">
      <div class="ui container">
        <div class="header item"> Flicks</div>
        <div class="item">
          <i class="home icon"></i>
          <%= link_to "Home", root_path %> 
        </div>
        <div class="right menu">
          <% if session[:user_id] %>
            <div class="item">
              <i class="address card icon"></i>
              <%= link_to "My Account", user_path(session[:user_id])%>
            </div>
            <div class="item">
              <i class="grid layout icon"></i>
              <%= link_to "Browse Movies", movies_path %>
            </div><%# <div class="control"> %>         
            <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
              <div class="item">
                <i class="sign out alternate icon"></i>
                <input type=submit value='logout'>
              </div>
            <% end %>     
          <% else %>
            <div class="item">
              <i class="sign in alternate icon"></i>
              <%= link_to "Sign In", login_path %>
            </div>
            <div class="item">
              <%= link_to "Create Account", new_user_path %>
            </div>
          <%end%>
        </div>
      </div>
    </div>   
  <header>
  <section class="section">
    <div class="container">
      <%= yield %>
    </div>
  </section>
  <footer class="footer">
    <div class="container">
    Copyright © 2019 Flicks. All rights reserved.
    </div>
  </footer>
  </body>
</html>

app/views/movies/_form.html.erb
<div>
    <%= form_for(@movie) do |m| %>
    <%= m.hidden_field :user_id %>
        <%= m.label "Title" %>
        <%= m.text_field :title%><br><br>
         <%= m.label "Description" %>
        <%= m.text_area :description %><br>
        <%= m.label "Trailer URL" %>
        <%= m.text_field :preview %><br>
        <%= m.label "Actors" %>
        <%= m.text_field :actors %><br>
        <%= m.label "Director" %>
        <%= m.text_field :director %><br>
        <%= m.label "Release Date (Nov 14, 2020)" %>
        <%= m.text_field :release_date %><br>
        <% @genres.each do |genre| %>
            <%= check_box_tag "movie[genres][]", genre.id, @movie.genres.include?(genre.id) %>
            <%= genre.name%><br>
            <%end%>
        <%= m.submit "create" %>
     <%end%>



</div>
 

app/views/movies/_video.html.erb
<iframe width="300" height="150" src="<%= preview %>" frameborder="0" allowfullscreen></iframe>

app/views/movies/edit.html.erb
<h1>Edit <%= @movie.title %></h1>
<%= render partial: 'form' %>

app/views/movies/index.html.erb
<h1> Browse Movies </h1>

<div class="container">
<h4>Browse Movies by: </h4>
    <%= form_tag("/movies", method: "get") do %>
       <p>Genre: </p> <%= select_tag "genre", options_from_collection_for_select(@genres, "name", "name"), include_blank: true %>
      <p>Upcoming movies only <%= check_box_tag "date"%> </p><br>
    <%= submit_tag "Filter" %>
    <%end%>
</div>

<% if @search_genre%>
    <h1><%= @search_genre%> Movies</h1>
<%end%>


<% @movies.each do |movie| %>
<div>
<h3><%= link_to movie.title, movie_path(movie) %></h3><br> 

<%= youtube_video movie.preview if movie.preview %>
<%end%>
</div>

app/views/movies/new.html.erb
<h1> New Movie </h1>

<%= render partial: 'form' %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<h2>In theaters <%= @movie.release_date %></h2>
<div>
    <% if @movie.preview != "" && @movie.preview != nil%>
    <%= youtube_video @movie.preview %>
    <%end%>
</div>
<div>
    <h5>Genres:</h5>
    <ul>
        <% @movie.genres.each do |genre|  %>
            <li><%= link_to genre.name, genre_path(genre) %></li>
        <%end%>
    </ul>
    <h5>Directed by <%= @movie.director %></h5><br>
    <h5>Starring <%= @movie.actors %></h5><br>
    <h5>Description:</h5><p> <%= @movie.description %></p><br>

</div>
<% if is_user_movie?(@movie) %>
    <%= link_to "Edit Movie", edit_user_movie_path(@movie.user, @movie)%>
<%end%>

app/views/users/_errors.html.erb
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      Submition failed:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'errors'%>
<%= form_for @user do |f| %>
    <h2>Edit your genre selection: </h2>

    <div>
        <% @genres.each do |genre| %>
            <%= check_box_tag "user[genres][]", genre.id, @user.genres.include?(genre.id) %>
        <%= genre.name%><br>
        <%end%>
  
    </div>

  <%= f.submit "submit" %>
<% end %>

app/views/users/new.html.erb
  <%= render partial: 'errors'%>


<%= form_for @user do |f| %>
  <%= link_to('Log in with Facebook!', '/auth/facebook') %>
  <div><%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br>
  </div>
  <h4>Select your favorite Movie Genres so we can recommend upcoming films! </h4>
  <div>
    <% @genres.each do |genre| %>
      <%= check_box_tag "user[genres][]", genre.id, @user.genres.include?(genre.id) %>
      <%= genre.name%><br>
    <%end%>
  
  </div>

  <%= f.submit "create" %>
<% end %>

app/views/users/show.html.erb
<div>
  <div class="ui attached segment">
  <div class="ui olive card">
    <div class="header">
      <div class="ui avatar image">
        <img src="<%= @user.image %>">
      </div>
      <%= @user.name %>
    </div>
    <div class="content"> 
      <div class="ui list">
        <div class="item">
          <i class="edit icon"></i>
          <%= link_to "Edit Fav-Genres", edit_user_path(@user) %>
        </div>
        <div class="item"> 
          <i class="upload icon"></i>
          <%= link_to "Add Movie to your collection", new_user_movie_path(@user) %>
        </div>
      </div>
    </div>
  </div>

<!-- browse movies logout and edit favorites should b in navbar -->

  <div class="ui fluid raised text container segment">
  <div class="ui small feed">
   <h2 class="ui header">Upcoming Movies You May Like </h2>
    <% @user.genres.each do |genre| %>
   
    <h5><%= genre.name %></h5>
    <% genre.movies.each do |movie| %>
      <%if movie.release_date != nil%>
      <%# <%if movie.release_date.to_date > Date.today && movie.release_date != nil%> 
        <div class="item">
          <div class="ui header">
            <%= link_to movie.title, movie_path(movie)%>
          </div>
          <div class="ui meta item">Release date- <%= movie.release_date %></div>
        <%= youtube_video movie.preview %> 
      <%end%>
      </div>
    <%end%>
    <%end%>
    <% if !@user.movies.empty?%>
    <h2 class="ui header">Your Movies: </h2>
    <% @user.movies.each do |movie| %>
      <button ><%= link_to movie.title, movie_path(movie)%></button>
    <%end%>
  <%end%>
  </div>
  </div>
  </div>
</div >